// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: hcmcore_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServiceClient interface {
	GetWorkerById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetOrganizationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetOrganizationByCreatorId(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetRoleById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetTeamById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetRolesFromOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetTeamsFromOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetOrganizationMembers(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetOrganizationJoinRequests(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetWorkerJoinRequests(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetJoinRequestById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetCompensationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetAdditionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetDeductionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetPayrollById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetAttendanceById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	GetShiftById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveWorker(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveMember(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveWorkerIdentityCard(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveRole(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveTeam(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveCompensation(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveAddition(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveDeduction(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SavePayroll(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveAttendance(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	SaveShift(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteWorkerById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteWorkerIdentityCardById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteOrganizationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteRoleById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteTeamById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteCompensationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteAdditionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteDeductionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
	DeleteShiftById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetWorkerById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getWorkerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetOrganizationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetOrganizationByCreatorId(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getOrganizationByCreatorId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetRoleById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getRoleById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetTeamById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getTeamById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetRolesFromOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getRolesFromOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetTeamsFromOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getTeamsFromOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetOrganizationMembers(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getOrganizationMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetOrganizationJoinRequests(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getOrganizationJoinRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetWorkerJoinRequests(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getWorkerJoinRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetJoinRequestById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getJoinRequestById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetCompensationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getCompensationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetAdditionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getAdditionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetDeductionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getDeductionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetPayrollById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getPayrollById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetAttendanceById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getAttendanceById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetShiftById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/getShiftById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveWorker(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveMember(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveWorkerIdentityCard(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveWorkerIdentityCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveOrganization(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveRole(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveTeam(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveCompensation(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveCompensation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveAddition(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveAddition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveDeduction(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveDeduction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SavePayroll(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/savePayroll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveAttendance(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveAttendance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SaveShift(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/saveShift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteWorkerById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteWorkerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteWorkerIdentityCardById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteWorkerIdentityCardById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteOrganizationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteRoleById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteRoleById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteTeamById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteTeamById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteCompensationById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteCompensationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteAdditionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteAdditionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteDeductionById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteDeductionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteShiftById(ctx context.Context, in *CoreServiceRequest, opts ...grpc.CallOption) (*CoreServiceResponse, error) {
	out := new(CoreServiceResponse)
	err := c.cc.Invoke(ctx, "/entities.CoreService/deleteShiftById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility
type CoreServiceServer interface {
	GetWorkerById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetOrganizationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetOrganizationByCreatorId(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetRoleById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetTeamById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetRolesFromOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetTeamsFromOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetOrganizationMembers(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetOrganizationJoinRequests(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetWorkerJoinRequests(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetJoinRequestById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetCompensationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetAdditionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetDeductionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetPayrollById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetAttendanceById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	GetShiftById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveWorker(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveMember(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveWorkerIdentityCard(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveRole(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveTeam(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveCompensation(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveAddition(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveDeduction(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SavePayroll(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveAttendance(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	SaveShift(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteWorkerById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteWorkerIdentityCardById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteOrganizationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteRoleById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteTeamById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteCompensationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteAdditionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteDeductionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	DeleteShiftById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoreServiceServer struct {
}

func (UnimplementedCoreServiceServer) GetWorkerById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerById not implemented")
}
func (UnimplementedCoreServiceServer) GetOrganizationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationById not implemented")
}
func (UnimplementedCoreServiceServer) GetOrganizationByCreatorId(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationByCreatorId not implemented")
}
func (UnimplementedCoreServiceServer) GetRoleById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleById not implemented")
}
func (UnimplementedCoreServiceServer) GetTeamById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamById not implemented")
}
func (UnimplementedCoreServiceServer) GetRolesFromOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolesFromOrganization not implemented")
}
func (UnimplementedCoreServiceServer) GetTeamsFromOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsFromOrganization not implemented")
}
func (UnimplementedCoreServiceServer) GetOrganizationMembers(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationMembers not implemented")
}
func (UnimplementedCoreServiceServer) GetOrganizationJoinRequests(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationJoinRequests not implemented")
}
func (UnimplementedCoreServiceServer) GetWorkerJoinRequests(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerJoinRequests not implemented")
}
func (UnimplementedCoreServiceServer) GetJoinRequestById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJoinRequestById not implemented")
}
func (UnimplementedCoreServiceServer) GetCompensationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompensationById not implemented")
}
func (UnimplementedCoreServiceServer) GetAdditionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdditionById not implemented")
}
func (UnimplementedCoreServiceServer) GetDeductionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeductionById not implemented")
}
func (UnimplementedCoreServiceServer) GetPayrollById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayrollById not implemented")
}
func (UnimplementedCoreServiceServer) GetAttendanceById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceById not implemented")
}
func (UnimplementedCoreServiceServer) GetShiftById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShiftById not implemented")
}
func (UnimplementedCoreServiceServer) SaveWorker(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWorker not implemented")
}
func (UnimplementedCoreServiceServer) SaveMember(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMember not implemented")
}
func (UnimplementedCoreServiceServer) SaveWorkerIdentityCard(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWorkerIdentityCard not implemented")
}
func (UnimplementedCoreServiceServer) SaveOrganization(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrganization not implemented")
}
func (UnimplementedCoreServiceServer) SaveRole(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRole not implemented")
}
func (UnimplementedCoreServiceServer) SaveTeam(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTeam not implemented")
}
func (UnimplementedCoreServiceServer) SaveCompensation(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCompensation not implemented")
}
func (UnimplementedCoreServiceServer) SaveAddition(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAddition not implemented")
}
func (UnimplementedCoreServiceServer) SaveDeduction(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDeduction not implemented")
}
func (UnimplementedCoreServiceServer) SavePayroll(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePayroll not implemented")
}
func (UnimplementedCoreServiceServer) SaveAttendance(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAttendance not implemented")
}
func (UnimplementedCoreServiceServer) SaveShift(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveShift not implemented")
}
func (UnimplementedCoreServiceServer) DeleteWorkerById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkerById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteWorkerIdentityCardById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkerIdentityCardById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteOrganizationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrganizationById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteRoleById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoleById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteTeamById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeamById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteCompensationById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompensationById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteAdditionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdditionById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteDeductionById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeductionById not implemented")
}
func (UnimplementedCoreServiceServer) DeleteShiftById(context.Context, *CoreServiceRequest) (*CoreServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShiftById not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetWorkerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetWorkerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getWorkerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetWorkerById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetOrganizationById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetOrganizationByCreatorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetOrganizationByCreatorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getOrganizationByCreatorId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetOrganizationByCreatorId(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getRoleById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetRoleById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetTeamById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetTeamById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getTeamById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetTeamById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetRolesFromOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetRolesFromOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getRolesFromOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetRolesFromOrganization(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetTeamsFromOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetTeamsFromOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getTeamsFromOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetTeamsFromOrganization(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetOrganizationMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetOrganizationMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getOrganizationMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetOrganizationMembers(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetOrganizationJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetOrganizationJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getOrganizationJoinRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetOrganizationJoinRequests(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetWorkerJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetWorkerJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getWorkerJoinRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetWorkerJoinRequests(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetJoinRequestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetJoinRequestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getJoinRequestById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetJoinRequestById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetCompensationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetCompensationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getCompensationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetCompensationById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetAdditionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetAdditionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getAdditionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetAdditionById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetDeductionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetDeductionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getDeductionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetDeductionById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetPayrollById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetPayrollById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getPayrollById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetPayrollById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetAttendanceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetAttendanceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getAttendanceById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetAttendanceById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetShiftById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetShiftById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/getShiftById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetShiftById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveWorker(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveMember(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveWorkerIdentityCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveWorkerIdentityCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveWorkerIdentityCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveWorkerIdentityCard(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveOrganization(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveRole(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveTeam(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveCompensation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveCompensation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveCompensation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveCompensation(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveAddition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveAddition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveAddition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveAddition(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveDeduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveDeduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveDeduction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveDeduction(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SavePayroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SavePayroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/savePayroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SavePayroll(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveAttendance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveAttendance(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SaveShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SaveShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/saveShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SaveShift(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteWorkerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteWorkerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteWorkerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteWorkerById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteWorkerIdentityCardById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteWorkerIdentityCardById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteWorkerIdentityCardById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteWorkerIdentityCardById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteOrganizationById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteRoleById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteRoleById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteTeamById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteTeamById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteTeamById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteTeamById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteCompensationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteCompensationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteCompensationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteCompensationById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteAdditionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteAdditionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteAdditionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteAdditionById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteDeductionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteDeductionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteDeductionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteDeductionById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteShiftById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteShiftById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.CoreService/deleteShiftById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteShiftById(ctx, req.(*CoreServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entities.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getWorkerById",
			Handler:    _CoreService_GetWorkerById_Handler,
		},
		{
			MethodName: "getOrganizationById",
			Handler:    _CoreService_GetOrganizationById_Handler,
		},
		{
			MethodName: "getOrganizationByCreatorId",
			Handler:    _CoreService_GetOrganizationByCreatorId_Handler,
		},
		{
			MethodName: "getRoleById",
			Handler:    _CoreService_GetRoleById_Handler,
		},
		{
			MethodName: "getTeamById",
			Handler:    _CoreService_GetTeamById_Handler,
		},
		{
			MethodName: "getRolesFromOrganization",
			Handler:    _CoreService_GetRolesFromOrganization_Handler,
		},
		{
			MethodName: "getTeamsFromOrganization",
			Handler:    _CoreService_GetTeamsFromOrganization_Handler,
		},
		{
			MethodName: "getOrganizationMembers",
			Handler:    _CoreService_GetOrganizationMembers_Handler,
		},
		{
			MethodName: "getOrganizationJoinRequests",
			Handler:    _CoreService_GetOrganizationJoinRequests_Handler,
		},
		{
			MethodName: "getWorkerJoinRequests",
			Handler:    _CoreService_GetWorkerJoinRequests_Handler,
		},
		{
			MethodName: "getJoinRequestById",
			Handler:    _CoreService_GetJoinRequestById_Handler,
		},
		{
			MethodName: "getCompensationById",
			Handler:    _CoreService_GetCompensationById_Handler,
		},
		{
			MethodName: "getAdditionById",
			Handler:    _CoreService_GetAdditionById_Handler,
		},
		{
			MethodName: "getDeductionById",
			Handler:    _CoreService_GetDeductionById_Handler,
		},
		{
			MethodName: "getPayrollById",
			Handler:    _CoreService_GetPayrollById_Handler,
		},
		{
			MethodName: "getAttendanceById",
			Handler:    _CoreService_GetAttendanceById_Handler,
		},
		{
			MethodName: "getShiftById",
			Handler:    _CoreService_GetShiftById_Handler,
		},
		{
			MethodName: "saveWorker",
			Handler:    _CoreService_SaveWorker_Handler,
		},
		{
			MethodName: "saveMember",
			Handler:    _CoreService_SaveMember_Handler,
		},
		{
			MethodName: "saveWorkerIdentityCard",
			Handler:    _CoreService_SaveWorkerIdentityCard_Handler,
		},
		{
			MethodName: "saveOrganization",
			Handler:    _CoreService_SaveOrganization_Handler,
		},
		{
			MethodName: "saveRole",
			Handler:    _CoreService_SaveRole_Handler,
		},
		{
			MethodName: "saveTeam",
			Handler:    _CoreService_SaveTeam_Handler,
		},
		{
			MethodName: "saveCompensation",
			Handler:    _CoreService_SaveCompensation_Handler,
		},
		{
			MethodName: "saveAddition",
			Handler:    _CoreService_SaveAddition_Handler,
		},
		{
			MethodName: "saveDeduction",
			Handler:    _CoreService_SaveDeduction_Handler,
		},
		{
			MethodName: "savePayroll",
			Handler:    _CoreService_SavePayroll_Handler,
		},
		{
			MethodName: "saveAttendance",
			Handler:    _CoreService_SaveAttendance_Handler,
		},
		{
			MethodName: "saveShift",
			Handler:    _CoreService_SaveShift_Handler,
		},
		{
			MethodName: "deleteWorkerById",
			Handler:    _CoreService_DeleteWorkerById_Handler,
		},
		{
			MethodName: "deleteWorkerIdentityCardById",
			Handler:    _CoreService_DeleteWorkerIdentityCardById_Handler,
		},
		{
			MethodName: "deleteOrganizationById",
			Handler:    _CoreService_DeleteOrganizationById_Handler,
		},
		{
			MethodName: "deleteRoleById",
			Handler:    _CoreService_DeleteRoleById_Handler,
		},
		{
			MethodName: "deleteTeamById",
			Handler:    _CoreService_DeleteTeamById_Handler,
		},
		{
			MethodName: "deleteCompensationById",
			Handler:    _CoreService_DeleteCompensationById_Handler,
		},
		{
			MethodName: "deleteAdditionById",
			Handler:    _CoreService_DeleteAdditionById_Handler,
		},
		{
			MethodName: "deleteDeductionById",
			Handler:    _CoreService_DeleteDeductionById_Handler,
		},
		{
			MethodName: "deleteShiftById",
			Handler:    _CoreService_DeleteShiftById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hcmcore_service.proto",
}
